Css canvas medical
AnthonyUrbina/c0822-code-solutions pull request #27
Opened 2022-08-30 06:22 UTC by AnthonyUrbina

![Screen Shot 2022-08-29 at 11 22 06 PM](https://user-images.githubusercontent.com/109625982/187364647-d802f815-fd8d-4c60-bb03-a12fa093ff4c.png)
![Screen Shot 2022-08-29 at 11 22 17 PM](https://user-images.githubusercontent.com/109625982/187364657-ad30b93a-6ef8-474e-af63-080ab9e8dd2d.png)
![Screen Shot 2022-08-29 at 11 22 19 PM](https://user-images.githubusercontent.com/109625982/187364667-a87823f3-aae1-4770-a615-e61acf89a2dd.png)

2022-08-30 21:46 UTC, codingcodymiller requested changes
Hey Anthony! This looks good, but your code is not really using layout classes, and it is important that you make proper use of them from this point forward. Please revise your solution to make use of `container`, `row` and `column-` classes appropriately. I encourage you to re-read `css-layout-classes` for a refresher on the concept, feel free to ask me any questions you might have on the concept, I am happy to help 🤓

2022-08-31 15:56 UTC, AnthonyUrbina commented
ok, thanks for not letting me slide on this. i think i started to panic which is why I decided to proceed this way. ill take my time and do it right. thanks, will reach out if i need to

2022-09-05 06:03 UTC, AnthonyUrbina commented
https://user-images.githubusercontent.com/109625982/188371063-c7519e93-89fb-498b-b995-8f940ad8b8c1.mov

2022-09-07 19:15 UTC, codingcodymiller requested changes

2022-09-07 19:15 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +    </div>
Layout classes should not be named after specific sections. You should have one `container` class, one `row` class that you can apply to any row in the layout, and one variant of `column-` classes for each size, that is reused for each element that needs to be that size.

2022-09-10 22:10 UTC, AnthonyUrbina commented
https://user-images.githubusercontent.com/109625982/189503434-30d70c40-cb86-46cb-9ac3-ac9fb9bd727a.mov

2022-09-12 18:30 UTC, codingcodymiller approved these changes
MUCH better!!! 🎉

2022-09-12 18:43 UTC, merged