completed css-ecommerce-page exercise
AnthonyUrbina/c0822-code-solutions pull request #39
Opened 2022-09-02 01:29 UTC by AnthonyUrbina

<img width="1434" alt="Screen Shot 2022-09-01 at 6 15 41 PM" src="https://user-images.githubusercontent.com/109625982/188039674-c0417240-55dc-49b6-925a-0421de5c185c.png">

2022-09-02 16:41 UTC, codingcodymiller requested changes

2022-09-02 16:41 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +}
Make this into a proper `column ` class. The `margin` should be applied to a separate rule for a separate class that you can add in addition to the `column` class, `column` classes should only have `flex-basis` or `width` applied to them.

2022-09-02 16:41 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +  padding-right: 80px;
This should be on a separate class, the `row` class should only have `display: flex` applied to it.

2022-09-03 04:57 UTC, AnthonyUrbina commented
okay sweet. fixed both. had to google how to add 2x classes lol. thanks for the help. 
![Screen Shot 2022-09-02 at 9 51 52 PM](https://user-images.githubusercontent.com/109625982/188256473-e0099490-07bc-44c5-8a6f-806c6667b24c.png)

2022-09-06 16:43 UTC, codingcodymiller requested changes

2022-09-06 17:02 UTC, AnthonyUrbina commented
okay, just fixed this

2022-09-07 19:07 UTC, codingcodymiller approved these changes

2022-09-07 23:19 UTC, merged