completed css-two-column-layout exercise
AnthonyUrbina/c0822-code-solutions pull request #43
Opened 2022-09-03 19:12 UTC by AnthonyUrbina

https://user-images.githubusercontent.com/109625982/188284843-f07f9d30-8bfc-4e32-8cb2-4897d2780994.mov

2022-09-06 16:39 UTC, codingcodymiller requested changes

2022-09-06 16:39 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
What happened to `.row`? You should never make numbered classes, it isn't descriptive of their purpose at all.

2022-09-06 16:39 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
This would be better named as `.text-center` or something to that effect

2022-09-06 20:37 UTC, AnthonyUrbina commented
got it
just fixed. i had done that to center rows but idk why i did it that way since i couldve used justify content

2022-09-07 19:16 UTC, codingcodymiller requested changes

2022-09-07 19:16 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
Again, this should be named `text-center` or something to that effect. `column-` classes only include `flex-basis` or `width`, anything else is not styling to apply to a `column-` class

2022-09-08 15:56 UTC, codingcodymiller approved these changes

2022-09-08 19:16 UTC, merged