completed string-manipulation-2 exercise
AnthonyUrbina/c0822-code-solutions pull request #44
Opened 2022-09-05 22:04 UTC by AnthonyUrbina

<img width="1434" alt="Screen Shot 2022-09-05 at 3 02 19 PM" src="https://user-images.githubusercontent.com/109625982/188516060-67970a61-c33c-4ed6-b3d2-fd6b91d4abcf.png">

2022-09-07 16:58 UTC, codingcodymiller requested changes

2022-09-07 16:58 UTC, codingcodymiller commented on string-manipulation-2/src/last-chars.js
> +      length = string.length;
If you do this above the loop, I think you can significantly simplify this code.

2022-09-08 21:55 UTC, AnthonyUrbina commented on string-manipulation-2/src/capitalize-word.js
> +    return container;
LOL just fixed this

2022-09-08 21:59 UTC, AnthonyUrbina commented on string-manipulation-2/src/num-vowels.js
> +  var container = null;
true

2022-09-09 17:36 UTC, codingcodymiller approved these changes

2022-09-09 19:07 UTC, merged